# Generated by Django 3.2.12 on 2023-05-22 22:46

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='prodect', verbose_name='upload Novel image')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Novel name')),
                ('language', models.CharField(choices=[('malayalam', 'malayalam'), ('english', 'english'), ('arabic', 'arabic')], max_length=50)),
                ('author', models.CharField(blank=True, max_length=20, null=True, verbose_name='Author Name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Novel price')),
            ],
            options={
                'verbose_name': 'Add Product',
                'verbose_name_plural': 'Add Products',
            },
        ),
    ]
